export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const CART_CHECKOUT_REQUEST = "CART_CHECKOUT_REQUEST";
export const CART_CHECKOUT_SUCCESS = "CART_CHECKOUT_SUCCESS";
export const CART_CHECKOUT_FAIL = "CART_CHECKOUT_FAIL";